// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZVyA7J-KFfH05Ecem1VhHvwadQNo_3vE',
    appId: '1:29348214727:web:2cd3feb9bc06cd7e5e0be2',
    messagingSenderId: '29348214727',
    projectId: 'music-6adf4',
    authDomain: 'music-6adf4.firebaseapp.com',
    storageBucket: 'music-6adf4.appspot.com',
    measurementId: 'G-1ET7Z40Q2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANhvG-ygQmNXSmam128T0R_XGbBigwbBY',
    appId: '1:29348214727:android:4190f9f6893851ad5e0be2',
    messagingSenderId: '29348214727',
    projectId: 'music-6adf4',
    storageBucket: 'music-6adf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX8HYgnJzll0jqu7mTR2JrFNVYzNuUb-g',
    appId: '1:29348214727:ios:941b973e85703b635e0be2',
    messagingSenderId: '29348214727',
    projectId: 'music-6adf4',
    storageBucket: 'music-6adf4.appspot.com',
    iosClientId: '29348214727-fjq1vbgeueul3n92u9sejk2e545h1o5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApp',
  );
}
